### ISSUE TITLE
Support cloud usage patterns

### ISSUE THREAD

**Issue by aftersought** [kevin-hanselman/dud#130]
This is a pretty involved feature request centred around cloud usage for fully versioned pipelines (i.e. where both code and the data are versioned, though a combo such as Git+Dud). The domain is more data engineering rather than pure ML, though ML quite often is one of the stages of larger pipeline.

Suppose that the business logic described by the pipeline is heavily reliant on cloud, i.e. successive stages are expected to be performed in the cloud on-demand. This necessitates storing data in the cloud as well. If the data usage is heavy, emulating a "local" solution such as shared disk is impractical due to bandwidth limitations (and also in certain sense runs counter to cloud-native ideology), and we shall assume that the on-demand workers will have to get their data independently from object storage.

Object storage cache backup is currently adopted by Dud by default, however that in itself does not accomplish the goal. The issue is in how `dud run` currently expects all the work to be done locally, with remote cache acting as a backup to local cache, and local stage files acting as synchronization objects. To work around this, the user is expected to manually execute the following on an on-demand cloud worker node:
- (git-)pull the stage files from remote
- (dud-)pull the required inputs
- run the job
- (dud-)commit the outputs to local cache
- (dud-)push the outputs to cloud storage
- (git-)commit the Dud state (stage files)
- (git-)push the stage files to remote

It would be great if Dud could do all of that in `dud run`, perhaps with a suitable set of flags!

I appreciate this goes counter to having Dud as a single-purpose tool, but this would lift a lot of weight for the developer in a very common (albeit advanced) use case. `dud run` at the moment is already a composite tool, devoted to pipelining rather than data versioning per se. This is natural, as pipelining works much better with full versioning of both code and data, and the feature request is a natural development of this functionality.

In this solution synchronisation between the stages is accomplished using Git -- a bit crude, but keeping in the spirit of reproducible pipelines. The resulting "pipeline log" can be squashed, so that's not really a major issue in my view, but certainly there are alternatives such as using cloud-based key-value stores to synchronize.

I would be interested in your thoughts on the matter.

**Comment by kevin-hanselman** [comment]
Thanks for your thorough feature request! I certainly see the benefits to this idea: Less commands for the developer to run, and a simpler path to automation and cloud compute from local dev pipelines. This idea is important to me, and I agree that we need better tooling in this space.

You also rightly point out the reasons not to implement this in Dud: Dud strives to do one thing well and exist orthogonally to other engineering tools such as source control systems and cloud provider APIs. Because [Dud strives to be a good UNIX citizen](https://github.com/kevin-hanselman/dud/blob/main/CONTRIBUTING.md#simple), I think the best way to accomplish your goal is to wrap Dud in shell scripts. For example, here's a pseudocode shell script derived from your steps above:

```sh
git fetch
git checkout $COMMIT_SHA
dud pull [stage(s) in question]
dud run [stage(s) in question]
dud commit [...]
git commit -am 'automated commit ...'
dud push [...]
git push
```

This script template could also be run in most CI/CD systems, thus abstracting the orchestration for developers.

I agree that this approach isn't perfect. As you point out above, Dud still requires artifacts to be staged locally, so developers have to think carefully about local caching and network speeds and costs. To address these drawbacks, my current opinion is that a new "cloud native" tool should be created, and Dud is not this tool. I'm still stewing on this idea, but I'd be happy to keep chatting about it.

For now, please consider the shell script approach as the recommended way to "extend" Dud's interoperability with source control and other systems. I'm going to close this issue, but please feel free to continue using it as a discussion thread. Thanks again for the feedback; I really appreciate it!
